### ISSUE TITLE
214.2 patch seems to have broken the mod

### ISSUE THREAD

**Issue by azegoca** [thedefside/BetterUI#61] opened 2023-03-13 20:00 UTC
The health bars here are not attached to anything, and seems to be stacking. All was working prior to 0.214.2 patch

![Screenshot 2023-03-13 112937](https://user-images.githubusercontent.com/29699691/224818280-be54977f-9b86-40c6-899d-f82abcf6e642.png)

**Comment by thedefside** [comment] 2023-03-13 23:43
Closed as duplicate of #60

**Closed by thedefside** 2023-03-13 23:43 UTC
Labels: duplicate
