### ISSUE TITLE
Chests are titled as "grave"

### ISSUE THREAD

**Issue by MonolithTMA** [thedefside/BetterUI#46] opened 2022-12-28 14:44 UTC
I installed v 2.4, and every chest I try to open says "grave." I can open them but can't see my inventory to transfer items to the chest. I went back to v 2.2.3, and the problem went away.

**Comment by thedefside** [comment] 2022-12-28 16:19
If you could do me a favor, install 2.4.0 again, load into the game, open a chest, they quit the game and send your logoutput.log file from your bepinex folder

**Comment by MonolithTMA** [comment] 2022-12-28 16:37
[LogOutput.log](https://github.com/thedefside/BetterUI/files/10315255/LogOutput.log)
There you go. Thanks for taking a look at it. Oddly, they are not titled "grave" now, but the other problem persists.

**Comment by thedefside** [comment] 2022-12-28 16:44
Here is the relevant error:

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterUI.Patches.ElementHelper.UpdateElement (GuiBar durabilityBar) (at <279117aadda34b069259cc5f4f2ca209>:0)
BetterUI.GameClasses.BetterInventoryGrid.PatchInventory (InventoryGrid& __instance, Player& player, ItemDrop+ItemData dragItem) (at <279117aadda34b069259cc5f4f2ca209>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <35c0f7aa1999477788815a7bf78200d7>:0)
InventoryGui.UpdateInventory (Player player) (at <35c0f7aa1999477788815a7bf78200d7>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)
```

@MonolithTMA I think this is probably going to be a conflict with one of your other mods. It might take some work to figure out which one. You have some outdated mods that are showing errors in your logs, with the biggest issue being Passive Powers. I would recommend you update or remove it first.

**Comment by MonolithTMA** [comment] 2022-12-28 16:52
Yeah, I know about the Passive Powers mod being outdated and throwing errors; I had to combine two powers mods to get the desired effect, which used to be handled by Passive Forsaken Powers from the Nexus. That one is really broken. I'll try some troubleshooting with 2.4.0 when I get a chance. Thanks!

**Comment by thedefside** [comment] 2022-12-28 16:57
An error from 1 mod could cause issues with other mods. That's why I recommended you remove those mods first. Let me know if you figure anything out, and we'll see if anybody else reports this problem.

**Comment by jtegtmeier** [comment] 2022-12-28 21:00
Not exactly sure if related (mod interactions are complex, as you say), but I was having issues with items disappearing when transferring items to graves/chests/equipment slots on `2.4.0`, `2.3.2` is still working well for me.

Modpack (includes mod configs): https://valheim.thunderstore.io/package/NaughtyWarriors/TheNaughtyIsles/

Quiver on BetterArchery disabled, not sure if there are any other notable configs set.

**Comment by Goldenrevolver** [comment] 2022-12-29 03:08
@jtegtmeier  that should not be caused by better ui reforged. you are using mods like 'Multi User Chest' which fundamentally changes how containers work, with mods like 'Quick Stack Store Sort Trash Restock' (which I am the author of) and Valheim Plus. start looking there. know that valheims multiplayer container system is incredibly fragile, so you should expect lost items when using multiple mods that affect them. it's impossible to write safe chest accesses when mods change every part of that access

**Comment by thedefside** [comment] 2022-12-29 03:12
Man, I was so excited when multi user chest came out. But then items started disappearing from our tombstones and we had to ditch it.

**Comment by Goldenrevolver** [comment] 2022-12-29 03:13
yes, the quote from multi user chests mod page is a good thing to go by

"Does it work with mods that add quick stacking / chest sorting?
Depends on the mod, see Incompatible Mods and Compatible Mods. If it not listed there, assume it doesn't work"

multi user chest has a custom patch for the original Quick Stack but not my new mod, so I should probably simply flag it as incompatible until they patch it (or I patch them)

**Comment by jtegtmeier** [comment] 2022-12-29 04:01
Ya, it seemed weird, but I was seeing a pretty strong correlation with BetterUI `2.4.0` not working with my setup, while the previous version's been working well for a while now. I'll likely remove multi-user chest too to avoid issues in the future. 👍 

I'll post a log if I give `2.4.0` a try again. Thanks for the help.

**Comment by MonolithTMA** [comment] 2022-12-31 20:31
> Here is the relevant error:
> 
> ```
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> BetterUI.Patches.ElementHelper.UpdateElement (GuiBar durabilityBar) (at <279117aadda34b069259cc5f4f2ca209>:0)
> BetterUI.GameClasses.BetterInventoryGrid.PatchInventory (InventoryGrid& __instance, Player& player, ItemDrop+ItemData dragItem) (at <279117aadda34b069259cc5f4f2ca209>:0)
> (wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
> InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <35c0f7aa1999477788815a7bf78200d7>:0)
> InventoryGui.UpdateInventory (Player player) (at <35c0f7aa1999477788815a7bf78200d7>:0)
> (wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)
> ```
> 
> @MonolithTMA I think this is probably going to be a conflict with one of your other mods. It might take some work to figure out which one. You have some outdated mods that are showing errors in your logs, with the biggest issue being Passive Powers. I would recommend you update or remove it first.

@thedefside Sadly, it was PassivePowers. I removed it, and everything works fine now. Thanks for your help. Have a happy new year!

**Comment by thedefside** [comment] 2022-12-31 20:35
@MonolithTMA thank you for the update.

**Closed by thedefside** 2022-12-31 20:35 UTC

**Comment by MonolithTMA** [comment] 2023-01-01 04:28
It started again without Passive Powers. I don't know what is causing it. It worked fine for a while and then started again. No other mods seem to be throwing errors., but I can't open a chest, and the log shows tons of errors when I try.
[LogOutput.log](https://github.com/thedefside/BetterUI/files/10328281/LogOutput.log)

**Comment by thedefside** [comment] 2023-01-01 04:32
@MonolithTMA can you try this file?

https://github.com/thedefside/BetterUI/releases/download/v2.3.3-pre-release/BetterUI.dll

**Comment by MonolithTMA** [comment] 2023-01-01 05:28
That worked! I logged in, and it worked. I was paranoid, so I quit the game and relaunched it several times, and it worked each time. Thank you!
