### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object Fish

### ISSUE THREAD

**Issue by Elllkere** [thedefside/BetterUI#39] opened 2022-12-16 12:00 UTC
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)

I have only betterUI 2.3.1

**Comment by thedefside** [comment] 2022-12-16 14:32
Try removing BetterUI and see if you still see that error. It seems like that is a bug with the game itself, not the mod.

**Comment by Elllkere** [comment] 2022-12-16 18:00
> Try removing BetterUI and see if you still see that error. It seems like that is a bug with the game itself, not the mod.

Yes, i tried it and when i dont have BetterUI i dont see errors

**Comment by thedefside** [comment] 2022-12-16 19:14
Can you gives the steps that are needed to recreate that error?

**Comment by Elllkere** [comment] 2022-12-16 19:30
> 

Starting the game (not load into the world) shows this and i think this happening when my character has fish in inventory, because i haven`t seen this error before but when i found perch it occurs

**Comment by Elllkere** [comment] 2022-12-16 20:07
and when i spent perch for craft error is gone

**Comment by thedefside** [comment] 2022-12-16 20:31
You're just starting the game? You haven't selected a character yet?

**Comment by Elllkere** [comment] 2022-12-16 20:36
> You're just starting the game? You haven't selected a character yet?

Yes, idk why it react with my inventory

**Comment by thedefside** [comment] 2022-12-16 20:44
Okay. I will look into it.

**Comment by Dalayeth** [comment] 2022-12-16 20:47
I was able to replicate this bug by adding a Perch fish to my inventory with "spawn Fish01" and then restarting the game. Logging out doesn't work. But when the game is restarted I do get 
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)
```

**Comment by thedefside** [comment] 2022-12-16 20:52
I was not able to recreate this. I spawned a fish `spawn Fish1`, then picked it up. I quit the game and then restarted. I do find it interesting that the fish shows up in the inventory with a star.
![image](https://user-images.githubusercontent.com/32403915/208186945-9159210b-5d17-469f-837b-e416a09c7091.png)

**Comment by thedefside** [comment] 2022-12-16 20:53
Can someone affected send me their config?

**Comment by Dalayeth** [comment] 2022-12-16 20:58
I was able to replicate by making a new profile in r2modman and installing only BetterUI Reforged. It made the default config and that's what I used.

**Comment by Elllkere** [comment] 2022-12-16 21:03
> Can someone affected send me their config?

i used default config, nothing changed

**Comment by Elllkere** [comment] 2022-12-16 21:04
> I was not able to recreate this. I spawned a fish `spawn Fish1`, then picked it up. I quit the game and then restarted. I do find it interesting that the fish shows up in the inventory with a star. ![image](https://user-images.githubusercontent.com/32403915/208186945-9159210b-5d17-469f-837b-e416a09c7091.png)

i had 3star fish :D

**Comment by Dalayeth** [comment] 2022-12-16 21:07
On my new profile with only BetterUI Reforged I made a new character in a new world and only added 1 perch to his inventory with the command when he spawned. Then restarted the game and had the error. I can't imagine what's causing this, but it might be the same thing causing a fish to have a star. Unfortunately the error message is useless.

**Comment by thedefside** [comment] 2022-12-16 21:57
New World, default config, BetterUI only. Perch in my inventory. I still can't seem to get this error to happen. 🤷‍♂️

**Comment by thedefside** [comment] 2022-12-16 22:03
@Elllkere I just noticed you have version 2.3.1, which is actually just 2.2.3 reuploaded. Can you try with the latest 2.3.2?

**Comment by Elllkere** [comment] 2022-12-16 22:16
> @Elllkere I just noticed you have version 2.3.1, which is actually just 2.2.3 reuploaded. Can you try with the latest 2.3.2?

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)

**Comment by thedefside** [comment] 2022-12-16 22:21
Do the errors keep repeating, or just those 2 times?

**Comment by thedefside** [comment] 2022-12-16 22:22
> On my new profile with only BetterUI Reforged I made a new character in a new world and only added 1 perch to his inventory with the command when he spawned. Then restarted the game and had the error. I can't imagine what's causing this, but it might be the same thing causing a fish to have a star. Unfortunately the error message is useless.

How many stars did your fish have?

**Comment by Elllkere** [comment] 2022-12-16 22:29
> Do the errors keep repeating, or just those 2 times?

2 times when game stared, also i used spawn Fish1 too for this time ang got 1star fish

**Comment by Dalayeth** [comment] 2022-12-18 16:44
Just saw this in the patch notes for 0.212.9 not sure why it only errors when BetterUI is installed but it seems like it was Valheim.
`* Fixed an error while viewing a character in the main menu that has a fish in its inventory`
I haven't tested on the new batch but it is on the beta branch if someone can confirm.

**Comment by Goldenrevolver** [comment] 2022-12-21 03:44
I just noticed the same @Dalayeth . that patch is now live, so if you can't reproduce the issue now, then we can probably close this issue

**Comment by Dalayeth** [comment] 2022-12-21 05:40
Sorry for the delay. I tested it a few of the ways I did last time to find the bug again but it seems fixed. It was Valheim all along. I would say this issue can be safely closed.

**Closed** 2022-12-26 22:42 UTC
