### ISSUE TITLE
2.4.0 breaks compatibility with EquipmentAndQuickSlots by RandyKnapp

### ISSUE THREAD

**Issue by DerNap** [thedefside/BetterUI#47] opened 2022-12-29 12:56 UTC
While reading in the patch notes about "Fix compatibility with ComfyQuickSlots and Odin's QOL (BruceOfTheBow & Goldenrevolver)" which I think is great, unfortunately the compatibility towards EquipmentAndQuickSlots completely broke. 
Since the latter based on ComfyQuickSlots (or maybe both of those share the same predecessor) I didn't expect an issue here.

When opening an inventory now, neither the equipment slot window is drawn correctly any more nor chest inventories will be rendered at all. Exception thrown is
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterUI.Patches.ElementHelper.UpdateElement (GuiBar durabilityBar) (at <279117aadda34b069259cc5f4f2ca209>:0)
BetterUI.GameClasses.BetterInventoryGrid.PatchInventory (InventoryGrid& __instance, Player& player, ItemDrop+ItemData dragItem) (at <279117aadda34b069259cc5f4f2ca209>:0)
(wrapper dynamic-method) InventoryGrid.DMD<InventoryGrid::UpdateGui>(InventoryGrid,Player,ItemDrop/ItemData)
InventoryGrid.UpdateInventory (Inventory inventory, Player player, ItemDrop+ItemData dragItem) (at <35c0f7aa1999477788815a7bf78200d7>:0)
EquipmentAndQuickSlots.InventoryGui_Patch+InventoryGui_UpdateInventory_Patch.Prefix (InventoryGui __instance, Player player) (at <ee231d9f9cd74d6f881aaab93fd2bb62>:0)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateInventory>(InventoryGui,Player)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)

For now I am going back to the 2.3.x version. I don't know if this problem has to be fixed on your side or an update in Randys mod is required. I hope this can be fixed on your side since 2.3 -> 2.4 update broke the compatibility.

**Comment by thedefside** [comment] 2022-12-29 13:52
I was not able to recreate this with just BetterUI and EAQS installed. Maybe a 3rd mod is involved?

![image](https://user-images.githubusercontent.com/32403915/209963124-f045908e-d6d3-41b4-ad02-d63a21a47b0a.png)

**Comment by thedefside** [comment] 2022-12-29 14:03
@DerNap can you send your config file for BetterUI so I can make sure I'm using the same settings as you?

**Comment by Kyamon** [comment] 2022-12-29 16:05
Seems to only be happening as a connected client and not in single player or as host.  
Friend having same issue while I am hosting without issue.

**Comment by thedefside** [comment] 2022-12-29 16:25
@Kyamon since both BetterUI and EAQS are client side only with no server sync, it seems unlikely that being the client to a host would be a factor. I think it's more likely that you and your friend have different config settings and that is why you don't see it. Would it be possible to send your friends config files for BetterUi and EAQS?

**Comment by thedefside** [comment] 2022-12-29 16:44
@DerNap would you be able to try testing [this](https://github.com/thedefside/BetterUI/releases/download/v2.3.3-pre-release/BetterUI.dll) version of BetterUI and see if you can reproduce the error again?

**Comment by DerNap** [comment] 2022-12-30 15:48
> ld you be

will do

**Comment by DerNap** [comment] 2022-12-30 15:49
> @DerNap would you be able to try testing [this](https://github.com/thedefside/BetterUI/releases/download/v2.3.3-pre-release/BetterUI.dll) version of BetterUI and see if you can reproduce the error again?

will do

**Comment by thedefside** [comment] 2023-01-03 13:31
This should be resolved by #51. Please update to v2,4,1 and let me know if the issue is gone.

**Closed** 2023-01-27 13:37 UTC
