### ISSUE TITLE
2.4.0 Breaks compatibility with ContentsWithin

### ISSUE THREAD

**Issue by Kyamon** [thedefside/BetterUI#48] opened 2022-12-29 16:03 UTC
Upon interacting with a container the inventory wont come up, but still shows the container contents.  
If you transfer any items into your inventory with hotkeys (ctrl+click) while your inventory is "hidden", it breaks item management, any item you try to pick up and move around your inventory will stick to your cursor until you logout. This disallows you from moving any other items or eating.

**Comment by thedefside** [comment] 2022-12-29 16:27
can you do me a favor and try [this](https://github.com/thedefside/BetterUI/releases/download/v2.3.3-pre-release/BetterUI.dll) version instead and let me know if you still have the issue?

**Comment by thedefside** [comment] 2022-12-29 16:33
@Kyamon which version of ContentsWithin are you using? The original by ComfyMods or the updated one from MSchmoecker

**Comment by thedefside** [comment] 2022-12-29 16:42
I was able to reproduce this issue with MSchmoecker's version of ContentsWithin and BetterUI 2.4.0. I tried with the preview version linked above and was not able to reproduce the issue. This leads me to believe PR #41 is the source of the problem.

**Comment by Kyamon** [comment] 2022-12-29 17:12
Yeah, it's the updated version from MSchmoecker.

**Comment by thedefside** [comment] 2023-01-03 13:30
This should be resolved by #51 . Please update to v2,4,1 and let me know if the issue is gone.

**Closed** 2023-01-27 13:38 UTC
